### ISSUE TITLE
MessageProtos

### ISSUE THREAD

**Issue by NickGibbons** [nadarrah15/RAFT#18]
This isn't a code issue or anything, I just have no idea how to work with ProtoBuffer :/

**Comment by nadarrah15** [comment]
Each of the four message types (AppendEntries, AppendEntriesResponse, RequestVote, and RequestVoteResponse) are now object types with a builder. Heres an example pulled from my code
''' java
MessageProtos.RequestVote.Builder requestVoteBuilder = MessageProtos.RequestVote.newBuilder();
        requestVoteBuilder.setTerm(currentTerm)
                .setCandidateId(id)
                .setLastLogIndex(log.size() - 1);
        if (log.size() > 0)
            requestVoteBuilder.setLastLogTerm(log.get(log.size() - 1).term);
        else
            requestVoteBuilder.setLastLogTerm(0);
        MessageProtos.RequestVote requestVote = requestVoteBuilder.build();
'''
