### ISSUE TITLE
QueueEntry

### ISSUE THREAD

**Issue by nadarrah15** [nadarrah15/RAFT#20]
``` java
public class QueueEntry<E> {

    private enum Type {
        Input, MessageIn, MessageOut
    }
```
What is the difference between ```Input``` and ```MessageIn```?

**Comment by nadarrah15** [comment]
Also, why is ```body``` generic, won't everything in the queue be a ```Message```

**Comment by Devilofawesomeness** [comment]
I initially intended to also place Client-based input into the queue

**Comment by Devilofawesomeness** [comment]
Input refers to local Client Input; Message refers to a Sent or Received message.
I altered the class structures so that Message now holds whether it is outgoing or ingoing through a boolean
